// src/models/StoryView.ts

export interface StoryView {
  StoryViewId: number;
  StoryId: number;
  UserId: number;
  ViewedAt?: Date;
}

export const sampleStoryViews: StoryView[] = [
  { StoryViewId: 1, StoryId: 1, UserId: 2 },
  { StoryViewId: 2, StoryId: 1, UserId: 3 },
  { StoryViewId: 3, StoryId: 1, UserId: 4 },
  { StoryViewId: 4, StoryId: 1, UserId: 5 },
  { StoryViewId: 5, StoryId: 1, UserId: 6 },
  { StoryViewId: 6, StoryId: 2, UserId: 1 },
  { StoryViewId: 7, StoryId: 2, UserId: 3 },
  { StoryViewId: 8, StoryId: 2, UserId: 5 },
  { StoryViewId: 9, StoryId: 2, UserId: 7 },
  { StoryViewId: 10, StoryId: 2, UserId: 9 },
  { StoryViewId: 11, StoryId: 3, UserId: 1 },
  { StoryViewId: 12, StoryId: 3, UserId: 2 },
  { StoryViewId: 13, StoryId: 3, UserId: 4 },
  { StoryViewId: 14, StoryId: 3, UserId: 6 },
  { StoryViewId: 15, StoryId: 3, UserId: 8 },
  { StoryViewId: 16, StoryId: 4, UserId: 2 },
  { StoryViewId: 17, StoryId: 4, UserId: 4 },
  { StoryViewId: 18, StoryId: 4, UserId: 6 },
  { StoryViewId: 19, StoryId: 4, UserId: 8 },
  { StoryViewId: 20, StoryId: 4, UserId: 10 },
  { StoryViewId: 21, StoryId: 5, UserId: 1 },
  { StoryViewId: 22, StoryId: 5, UserId: 3 },
  { StoryViewId: 23, StoryId: 5, UserId: 5 },
  { StoryViewId: 24, StoryId: 5, UserId: 7 },
  { StoryViewId: 25, StoryId: 5, UserId: 9 },
  { StoryViewId: 26, StoryId: 6, UserId: 2 },
  { StoryViewId: 27, StoryId: 6, UserId: 4 },
  { StoryViewId: 28, StoryId: 6, UserId: 6 },
  { StoryViewId: 29, StoryId: 6, UserId: 8 },
  { StoryViewId: 30, StoryId: 6, UserId: 10 },
  { StoryViewId: 31, StoryId: 7, UserId: 1 },
  { StoryViewId: 32, StoryId: 7, UserId: 3 },
  { StoryViewId: 33, StoryId: 7, UserId: 5 },
  { StoryViewId: 34, StoryId: 7, UserId: 7 },
  { StoryViewId: 35, StoryId: 7, UserId: 9 },
  { StoryViewId: 36, StoryId: 8, UserId: 2 },
  { StoryViewId: 37, StoryId: 8, UserId: 4 },
  { StoryViewId: 38, StoryId: 8, UserId: 6 },
  { StoryViewId: 39, StoryId: 8, UserId: 8 },
  { StoryViewId: 40, StoryId: 8, UserId: 10 },
  { StoryViewId: 41, StoryId: 9, UserId: 1 },
  { StoryViewId: 42, StoryId: 9, UserId: 3 },
  { StoryViewId: 43, StoryId: 9, UserId: 5 },
  { StoryViewId: 44, StoryId: 9, UserId: 7 },
  { StoryViewId: 45, StoryId: 9, UserId: 9 },
  { StoryViewId: 46, StoryId: 10, UserId: 2 },
  { StoryViewId: 47, StoryId: 10, UserId: 4 },
  { StoryViewId: 48, StoryId: 10, UserId: 6 },
  { StoryViewId: 49, StoryId: 10, UserId: 8 },
  { StoryViewId: 50, StoryId: 10, UserId: 10 },
  { StoryViewId: 51, StoryId: 11, UserId: 2 },
  { StoryViewId: 52, StoryId: 11, UserId: 3 },
  { StoryViewId: 53, StoryId: 11, UserId: 4 },
  { StoryViewId: 54, StoryId: 11, UserId: 5 },
  { StoryViewId: 55, StoryId: 11, UserId: 6 },
  { StoryViewId: 56, StoryId: 12, UserId: 1 },
  { StoryViewId: 57, StoryId: 12, UserId: 3 },
  { StoryViewId: 58, StoryId: 12, UserId: 5 },
  { StoryViewId: 59, StoryId: 12, UserId: 7 },
  { StoryViewId: 60, StoryId: 12, UserId: 9 },
  { StoryViewId: 61, StoryId: 13, UserId: 1 },
  { StoryViewId: 62, StoryId: 13, UserId: 2 },
  { StoryViewId: 63, StoryId: 13, UserId: 4 },
  { StoryViewId: 64, StoryId: 13, UserId: 6 },
  { StoryViewId: 65, StoryId: 13, UserId: 8 },
  { StoryViewId: 66, StoryId: 14, UserId: 2 },
  { StoryViewId: 67, StoryId: 14, UserId: 4 },
  { StoryViewId: 68, StoryId: 14, UserId: 6 },
  { StoryViewId: 69, StoryId: 14, UserId: 8 },
  { StoryViewId: 70, StoryId: 14, UserId: 10 },
  { StoryViewId: 71, StoryId: 15, UserId: 1 },
  { StoryViewId: 72, StoryId: 15, UserId: 3 },
  { StoryViewId: 73, StoryId: 15, UserId: 5 },
  { StoryViewId: 74, StoryId: 15, UserId: 7 },
  { StoryViewId: 75, StoryId: 15, UserId: 9 },
  { StoryViewId: 76, StoryId: 16, UserId: 2 },
  { StoryViewId: 77, StoryId: 16, UserId: 4 },
  { StoryViewId: 78, StoryId: 16, UserId: 6 },
  { StoryViewId: 79, StoryId: 16, UserId: 8 },
  { StoryViewId: 80, StoryId: 16, UserId: 10 },
  { StoryViewId: 81, StoryId: 17, UserId: 1 },
  { StoryViewId: 82, StoryId: 17, UserId: 3 },
  { StoryViewId: 83, StoryId: 17, UserId: 5 },
  { StoryViewId: 84, StoryId: 17, UserId: 7 },
  { StoryViewId: 85, StoryId: 17, UserId: 9 },
  { StoryViewId: 86, StoryId: 18, UserId: 2 },
  { StoryViewId: 87, StoryId: 18, UserId: 4 },
  { StoryViewId: 88, StoryId: 18, UserId: 6 },
  { StoryViewId: 89, StoryId: 18, UserId: 8 },
  { StoryViewId: 90, StoryId: 18, UserId: 10 },
  { StoryViewId: 91, StoryId: 19, UserId: 1 },
  { StoryViewId: 92, StoryId: 19, UserId: 3 },
  { StoryViewId: 93, StoryId: 19, UserId: 5 },
  { StoryViewId: 94, StoryId: 19, UserId: 7 },
  { StoryViewId: 95, StoryId: 19, UserId: 9 },
  { StoryViewId: 96, StoryId: 20, UserId: 2 },
  { StoryViewId: 97, StoryId: 20, UserId: 4 },
  { StoryViewId: 98, StoryId: 20, UserId: 6 },
  { StoryViewId: 99, StoryId: 20, UserId: 8 },
  { StoryViewId: 100, StoryId: 20, UserId: 10 },
];
