export interface User {
  UserId: number; // Hoặc string nếu bạn dùng UUID
  Username: string;
  Email: string;
  Password?: string; // Thường không trả về password cho UI
  FullName: string;
  Bio: string;
  Website?: string;
  PhoneNumber?: string;
  Gender: 'MALE' | 'FEMALE' | 'OTHER';
  Birthday?: string; // Hoặc Date nếu bạn muốn xử lý ngày tháng năm
  ProfilePicture?: string;
  PrivateAccount: boolean;
  Status: 'ACTIVE' | 'INACTIVE' | 'BANNED';
  Verified: boolean;
}

export const sampleUsers: User[] = [
  {
    UserId: 1,
    Username: 'john_doe',
    Email: 'john.doe@example.com',
    FullName: 'John Doe',
    Bio: 'Photographer and traveler.',
    Website: 'johndoe.com',
    PhoneNumber: '123-456-7890',
    Gender: 'MALE',
    Birthday: '1990-05-15',
    ProfilePicture: 'john_doe.jpg',
    PrivateAccount: false,
    Status: 'ACTIVE',
    Verified: true,
  },
  {
    UserId: 2,
    Username: 'jane_smith',
    Email: 'jane.smith@example.com',
    FullName: 'Jane Smith',
    Bio: 'Fitness enthusiast and blogger.',
    Website: 'janesmithfitness.com',
    PhoneNumber: '987-654-3210',
    Gender: 'FEMALE',
    Birthday: '1992-10-20',
    ProfilePicture: 'jane_smith.jpg',
    PrivateAccount: true,
    Status: 'ACTIVE',
    Verified: false,
  },
  {
    UserId: 3,
    Username: 'peter_jones',
    Email: 'peter.jones@example.com',
    FullName: 'Peter Jones',
    Bio: 'Software developer and gamer.',
    Website: 'peterjones.dev',
    PhoneNumber: '555-123-4567',
    Gender: 'MALE',
    Birthday: '1988-03-01',
    ProfilePicture: 'peter_jones.jpg',
    PrivateAccount: false,
    Status: 'ACTIVE',
    Verified: true,
  },
  // Thêm các user khác vào đây
  {
    UserId: 4,
    Username: 'linda_brown',
    Email: 'linda.brown@example.com',
    FullName: 'Linda Brown',
    Bio: 'Bookworm and nature lover.',
    Website: 'lindabrownreads.com',
    PhoneNumber: '111-222-3333',
    Gender: 'FEMALE',
    Birthday: '1995-07-08',
    ProfilePicture: 'linda_brown.jpg',
    PrivateAccount: false,
    Status: 'BANNED',
    Verified: false,
  },
  {
    UserId: 5,
    Username: 'david_wilson',
    Email: 'david.wilson@example.com',
    FullName: 'David Wilson',
    Bio: 'Marketing professional and food lover.',
    Website: 'davidwilsonmarketing.com',
    PhoneNumber: '444-555-6666',
    Gender: 'MALE',
    Birthday: '1993-12-25',
    ProfilePicture: 'david_wilson.jpg',
    PrivateAccount: false,
    Status: 'INACTIVE',
    Verified: false,
  },
  {
    UserId: 6,
    Username: 'sarah_miller',
    Email: 'sarah.miller@example.com',
    FullName: 'Sarah Miller',
    Bio: 'Artist and designer.',
    Website: 'sarahmillerart.com',
    PhoneNumber: '777-888-9999',
    Gender: 'FEMALE',
    Birthday: '1991-09-03',
    ProfilePicture: 'sarah_miller.jpg',
    PrivateAccount: false,
    Status: 'ACTIVE',
    Verified: true,
  },
  {
    UserId: 7,
    Username: 'michael_davis',
    Email: 'michael.davis@example.com',
    FullName: 'Michael Davis',
    Bio: 'Musician and composer.',
    Website: 'michaeldavismusic.com',
    PhoneNumber: '666-777-8888',
    Gender: 'MALE',
    Birthday: '1987-02-14',
    ProfilePicture: 'michael_davis.jpg',
    PrivateAccount: true,
    Status: 'ACTIVE',
    Verified: false,
  },
  {
    UserId: 8,
    Username: 'emily_white',
    Email: 'emily.white@example.com',
    FullName: 'Emily White',
    Bio: 'Travel blogger and writer.',
    Website: 'emilywhitetravels.com',
    PhoneNumber: '333-444-5555',
    Gender: 'FEMALE',
    Birthday: '1994-06-22',
    ProfilePicture: 'emily_white.jpg',
    PrivateAccount: false,
    Status: 'ACTIVE',
    Verified: true,
  },
  {
    UserId: 9,
    Username: 'kevin_anderson',
    Email: 'kevin.anderson@example.com',
    FullName: 'Kevin Anderson',
    Bio: 'Financial analyst and investor.',
    Website: 'kevinandersonfinance.com',
    PhoneNumber: '222-333-4444',
    Gender: 'MALE',
    Birthday: '1989-11-10',
    ProfilePicture: 'kevin_anderson.jpg',
    PrivateAccount: false,
    Status: 'ACTIVE',
    Verified: false,
  },
  {
    UserId: 10,
    Username: 'jessica_taylor',
    Email: 'jessica.taylor@example.com',
    FullName: 'Jessica Taylor',
    Bio: 'Teacher and volunteer.',
    Website: 'jessicatayloreducation.com',
    PhoneNumber: '888-999-0000',
    Gender: 'FEMALE',
    Birthday: '1996-04-28',
    ProfilePicture: 'jessica_taylor.jpg',
    PrivateAccount: true,
    Status: 'ACTIVE',
    Verified: true,
  },
];
